hoodiehq/hoodie-app-tracker

www/about.html, www/account.html, www/index.html
when tests pass, this is good to merge :+1:
=> /hoodie/bundle.js is now /hoodie/client.js

www/account.html, www/assets/app.css
Small fixes I wanted to take care of. Making buttons same height as inputs.
Making some inputs taller inside user settings.
=> Fixing button height next to inputs. Remove a p tag

public/assets/app.css
I think we don’t use these any more
=> remove obsolete utils

public/assets/app.css
I tried the green and it actually didn't look too contrasty when the font wasn't bold. So I am using a decent shade of blue now. Let me know if it looks good!
I used this tool: http://leaverou.github.io/contrast-ratio/#%23436EEE-on-white
=> fix: change highlighted color

public/account.html, public/assets/app.css
I messed up how links worked when I made the color changes, this should fix it.
=> fix: links color, hover, and active states, etc

public/assets/app.css
=> fix: Some new visual bugs caused by recent changes

test/store-test.js
Hey :),
I added all tests that were solely dependant on `hoodie.store` to  the new [hoodie-store](https://github.com/hoodiehq/hoodie-store) repository. 
I think they are not needed here then anymore in the future.
Best,
Finn
=> test: remove tests covered by hoodie-store

public/about.html, public/account.html, public/assets/app.css, public/assets/js/a11y-announce.js, public/assets/js/account.js
WIP just getting this up as an update.
=> Screenreader testing tweaks

test/store-test.js
=> unskip ".findAll() objects after signin"

package.json
hoodie@12 is our first camp release :v: get it with `npm install --save hoodie@camp`
=> Install hoodie from npm

README.md
i think maybe the folder structure has been changed?
=> correct the frond end files path

LICENSE
[Closes 57](https://github.com/hoodiehq/camp/issues/57#event-821928843)
=> chore(LICENSE): use standard Apache V2.0 text

public/assets/js/account.js
=> close form after email/password update

deployment.md
=> deploy with now (deployment docs)

public/assets/js/account.js
=> Redirect to tracker after login (#17)

package.json, public/assets/js/account.js, public/assets/js/common.js, public/assets/js/index.js, test/connection-status-test.js, test/index.js
part of https://github.com/hoodiehq/camp/issues/101, closes https://github.com/hoodiehq/hoodie-app-tracker/pull/118
Once the new `hoodie` version is released, update `package.json` accordingly
=> async hoodie

deployment.md
was pointing to my own repo instead of hoodiehq. this will fix that!
=> update deploy to bluemix url to main repo

LICENSE
Added current year closes,  closes hoodiehq/camp#131
=> Update License and closes hoodiehq/camp#131

public/assets/app.css, public/assets/js/index.js, public/index.html
counts the number of items in the list
=> added list item count

public/assets/js/account.js
bugfix for [#162](https://github.com/hoodiehq/hoodie-app-tracker/issues/162)
=> bugfix for change Email undefined in account settings
